name: CMake

on:
  create:
    tags:
      - v1.**

jobs:
  release-project:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
#       - name: Archive content
#         uses: thedoctor0/zip-release@master
#         with:
#            filename: src/main.cpp
      - name: print event name
        run: echo ${{ github.event_name }}
      # - name: create release
      #   id: createRelease
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release${{ github.ref }}
      # - name: check
      #   working-directory: ${{ github.workspace }}
      #   run: |
      #     ls
      #     pwd
      #     echo ${{ github.workspace }}/src/
      # - name: Upload Release Assets
      #   uses: alexellis/upload-assets@0.4.0
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     asset_paths: '["./src/*"]'
