name: CMake

on:
  pull_request:
    branches: ["main","test"]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v1
      - name: test
        run: git diff origin/test -- ./src
#       - uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - uses: docker/build-push-action@v3
#         with:
#           context: .
#           cache-from: |
#                       type=registry,ref=ghcr.io/app:cache
#                       type=gha
#           cache-to: |
#                       type=registry,ref=ghcr.io/app:cache,mode=max
#                       type=gha,mode=max
#           tags: name/app:latest
#           push: true
#       - name: docker test
#         run: |
#           docker images


      
