name: CMake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["test"]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: docker/login-action@v2
      - name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: 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


      
