name: CMake

on:
  push:
  pull_request:
    branches: ["main","test"]
  workflow_dispatch:
jobs:
  x86build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v1
      - name: test
        id: test1
        run: |
          git diff origin/test -- ./src
          git log
          git checkout test1.0
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: src/CMakeLists.txt
  arm64build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v1
      - name: test
        id: test1
        run: git diff origin/test -- ./src
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: src/main.cpp
  macosBuild:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v1
      - name: test
        id: test1
        run: git diff origin/test -- ./src
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: .github/workflows/
  release:
    runs-on: [ubuntu-latest]
    needs: [macosBuild, arm64build, x86build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workspace }}
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{ github.workspace }}


      
